"""bh-01's design tokens as Textual themes. Generated by scripts/sync-tokens; do not edit.

From bh-01's `dist/tokens/colors.css` and `dist/themes/default.css`, snapshotted in
`bh-02/plugins/tui-cordis-plugin/bh-01-tokens/`. Every `--bh-color-<role>` is the variable
`$bh-<role>` in both themes.
"""

from textual.theme import Theme

__all__ = ["DARK", "DARK_VARIABLES", "LIGHT", "LIGHT_VARIABLES", "dark", "light"]

DARK = "bh-01-dark"
LIGHT = "bh-01-light"

DARK_VARIABLES: dict[str, str] = {
    "bh-bg": "#0D0C0A",
    "bh-surface": "#151412",
    "bh-surface-raised": "#222120",
    "bh-surface-overlay": "#222120",
    "bh-surface-recessed": "#111110",
    "bh-text": "#C8C4BC",
    "bh-text-muted": "#5A5754",
    "bh-text-tertiary": "#5A5754",
    "bh-text-inverse": "#0D0C0A",
    "bh-text-bright": "#FFFFFF",
    "bh-primary": "#FF6B35",
    "bh-primary-hover": "#FF8B4D",
    "bh-primary-active": "#FFAA75",
    "bh-primary-text": "#0D0C0A",
    "bh-primary-glow": "#FF6B3526",
    "bh-secondary": "#222120",
    "bh-secondary-hover": "#2A2826",
    "bh-secondary-active": "#5A5754",
    "bh-secondary-text": "#C8C4BC",
    "bh-accent": "#FF6B35",
    "bh-accent-secondary": "#5DAFD6",
    "bh-accent-tertiary": "#E92C63",
    "bh-success": "#5DAFD6",
    "bh-success-dim": "#5DAFD626",
    "bh-warning": "#F83E1F",
    "bh-warning-dim": "#F83E1F26",
    "bh-danger": "#E92C63",
    "bh-danger-hover": "#F04E77",
    "bh-danger-active": "#F47090",
    "bh-danger-text": "#0D0C0A",
    "bh-border": "#2A2826",
    "bh-border-muted": "#1E1D1B",
    "bh-border-bright": "#5A5754",
    "bh-ring": "#FF6B35",
    "bh-link": "#5DAFD6",
    "bh-link-hover": "#FF6B35",
    "bh-link-subtle": "#C8C4BC",
    "bh-link-subtle-hover": "#5DAFD6",
}


LIGHT_VARIABLES: dict[str, str] = {
    "bh-bg": "#F0ECE4",
    "bh-surface": "#E8E4DC",
    "bh-surface-raised": "#F5F2EC",
    "bh-surface-overlay": "#FFFFFF",
    "bh-surface-recessed": "#DDD9D1",
    "bh-text": "#1A1A1A",
    "bh-text-muted": "#5A5754",
    "bh-text-tertiary": "#5A5754",
    "bh-text-inverse": "#FFFFFF",
    "bh-text-bright": "#000000",
    "bh-primary": "#FF6B35",
    "bh-primary-hover": "#E85A28",
    "bh-primary-active": "#C4461C",
    "bh-primary-text": "#FFFFFF",
    "bh-primary-glow": "#FF6B351E",
    "bh-secondary": "#E8E4DC",
    "bh-secondary-hover": "#DDD9D1",
    "bh-secondary-active": "#CCC7BD",
    "bh-secondary-text": "#1A1A1A",
    "bh-accent": "#FF6B35",
    "bh-accent-secondary": "#5DAFD6",
    "bh-accent-tertiary": "#E92C63",
    "bh-success": "#5DAFD6",
    "bh-success-dim": "#5DAFD626",
    "bh-warning": "#F83E1F",
    "bh-warning-dim": "#F83E1F26",
    "bh-danger": "#E92C63",
    "bh-danger-hover": "#D11A50",
    "bh-danger-active": "#B8163F",
    "bh-danger-text": "#FFFFFF",
    "bh-border": "#CCC7BD",
    "bh-border-muted": "#DDD9D1",
    "bh-border-bright": "#A8A39B",
    "bh-ring": "#FF6B35",
    "bh-link": "#5DAFD6",
    "bh-link-hover": "#FF6B35",
    "bh-link-subtle": "#5A5754",
    "bh-link-subtle-hover": "#5DAFD6",
}


def dark() -> Theme:
    """Return bh-01's dark theme."""
    return Theme(
        name=DARK,
        primary="#FF6B35",
        secondary="#5DAFD6",
        accent="#FF6B35",
        warning="#F83E1F",
        error="#E92C63",
        success="#5DAFD6",
        foreground="#C8C4BC",
        background="#0D0C0A",
        surface="#151412",
        panel="#222120",
        dark=True,
        variables=dict(DARK_VARIABLES),
    )


def light() -> Theme:
    """Return bh-01's light theme."""
    return Theme(
        name=LIGHT,
        primary="#FF6B35",
        secondary="#5DAFD6",
        accent="#FF6B35",
        warning="#F83E1F",
        error="#E92C63",
        success="#5DAFD6",
        foreground="#1A1A1A",
        background="#F0ECE4",
        surface="#E8E4DC",
        panel="#F5F2EC",
        dark=False,
        variables=dict(LIGHT_VARIABLES),
    )
